travis:
  secure:
    BINSTAR_TOKEN: kJICu/GjcuH68Bhsp3s8OZue7ljvZx0hlMcBd7fgxuJ81HLis33f7BOLE7dRxm+GBUlOcQ2HGkKFX4iD81HEPqQeLqepJ3TkaKetFIrKiIfy6KWv56alspMKy35cd9p5EvRAGxGnVrwlmVIBfrrHICaL1mGDZr3pmf+0rhnugBLaZSx6F7VPjsXgg6IeG6Lsjwh6pFxKcPaO0aYurCNdPTGt0Z/QPtzjJsjfsgsDISvvB+RYdScTdJ71LgusUyePO38rMUzgHWkI8J/92ZUyma1JWBvLvImCLWtPHC6l3lnTusAkN7HzvNuIdLB5wVEzfw9bb5i8XN9s33QDjsSA7/3+eTos6fHH1gmVsLG8Vgqr0fayg1YH5xkHajQBjFc0Rr8nrlomphRe6FKUeDk+39jkjwUEfR/4szKKzV4ThLGEYpwtLy9UYZOp7w5XWR+My9OIEAMgWxGhmM/hyj5kQH/b1jOmsldRswicBQY/GeqjwNzOjPchYPRLj5APJS8oBBe+Ve1bYwZBaKpH3FNGJeoc3itF/C+tORfFPvpoPtOocyPgMJxi2QUbjvJM+UlzV9I+0fqfAAEsrBYFvFDUtKva/mET/eDq8pxwFaXT58QvArynoUJ6a2x04VeBBGxEJj2Dqc0E4dBjc23Gpm9gNZdrFpkm5IFoT3Y9n+r0Zac=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
